DROP TABLE LOCALIDAD;
CREATE TABLE LOCALIDAD(
    IDLOCALIDAD    INTEGER PRIMARY KEY AUTOINCREMENT
    ,HID             INTEGER 
    ,NOMBRE          VARCHAR(100) NOT NULL
    ,ESTADO          VARCHAR(1) DEFAULT 'A'
    ,IDLOCALIDADTIPO VARCHAR(1) DEFAULT NULL
    ,CONSTRAINT fk_HID
    FOREIGN KEY (HID) REFERENCES LOCALIDAD(IDLOCALIDAD)
    ,CONSTRAINT fk_IDLOCALIDADTIPO
    FOREIGN KEY (IDLOCALIDADTIPO) REFERENCES LOCALIDAD(IDLOCALIDAD)

);

INSERT INTO LOCALIDAD(HID,NOMBRE) VALUES (NULL, "PAIS");
INSERT INTO LOCALIDAD(HID,NOMBRE) VALUES (1, "PROVINCIA");
INSERT INTO LOCALIDAD(HID,NOMBRE) VALUES (1, "ZONA");
INSERT INTO LOCALIDAD(HID,NOMBRE) VALUES (2, "CANTON");
INSERT INTO LOCALIDAD(HID,NOMBRE) VALUES (4, "CIUDAD");
INSERT INTO LOCALIDAD(HID,NOMBRE) VALUES (5, "PARROQUIA");

INSERT INTO LOCALIDAD(HID,NOMBRE,IDLOCALIDADTIPO) VALUES (NULL, "ECUADOR",1);
INSERT INTO LOCALIDAD(HID,NOMBRE,IDLOCALIDADTIPO) VALUES (NULL, "COLOMBIA",1);

INSERT INTO LOCALIDAD(HID,NOMBRE,IDLOCALIDADTIPO) VALUES (7, "PICHINCHA",2);
INSERT INTO LOCALIDAD(HID,NOMBRE,IDLOCALIDADTIPO) VALUES (7, "IMBABURA",2);

INSERT INTO LOCALIDAD(HID,NOMBRE,IDLOCALIDADTIPO) VALUES (9, "CAYAMBE",4);
INSERT INTO LOCALIDAD(HID,NOMBRE,IDLOCALIDADTIPO) VALUES (9, "QUITO",4);


INSERT INTO LOCALIDAD(HID,NOMBRE,IDLOCALIDADTIPO) VALUES (12, "QUITO",5);
INSERT INTO LOCALIDAD(HID,NOMBRE,IDLOCALIDADTIPO) VALUES (12, "QUITUMBE",5);

INSERT INTO LOCALIDAD(HID,NOMBRE,IDLOCALIDADTIPO) VALUES (13, "QUEVEDO",6);
INSERT INTO LOCALIDAD(HID,NOMBRE,IDLOCALIDADTIPO) VALUES (13, "INAQUITO",6);

SELECT * FROM LOCALIDAD;
SELECT NOMBRE FROM LOCALIDAD WHERE IDLOCALIDADTIPO = 1;






